# Generated by Django 5.0.2 on 2024-02-19 09:49

import django.core.validators
import django_ckeditor_5.fields
import modules.recipe.models
import services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_ingredientgroup_ingredientquantitygroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking',
            field=models.CharField(default='', max_length=4, verbose_name='Время готовки'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(choices=[('часов', 'часов'), ('минут', 'минут')], default='hours', max_length=10, verbose_name='минут/часов'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', max_length=110, verbose_name='Описание блюда'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('легкая', 'легкая сложность'), ('средняя', 'средняя сложность'), ('тяжелая', 'тяжелая сложность')], default='hours', max_length=10, verbose_name='Сложность рецепта'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Мин. количество порций 1')], verbose_name='Количество порций'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='images',
            field=models.FileField(blank=True, default='images/no-images.jpg', null=True, upload_to=modules.recipe.models.get_file_path, validators=[services.validators.validate_file_extension], verbose_name='Превью рецепта'),
        ),
    ]
