# Generated by Django 5.0.2 on 2024-02-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_ingredient_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredient',
            table=None,
        ),
    ]
