# Generated by Django 5.0.2 on 2024-02-20 10:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_ingredient_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description_at',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', max_length=150, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='keywords_at',
            field=models.CharField(default='', max_length=150, verbose_name='Теги'),
        ),
    ]
